# Generated by Django 2.2.4 on 2019-08-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.CharField(help_text='Stravas number user', max_length=10, unique=True)),
                ('first_name', models.CharField(help_text='User name', max_length=30)),
                ('second_name', models.CharField(help_text='User second name', max_length=30)),
                ('login', models.CharField(help_text='User login', max_length=20, unique=True)),
                ('password', models.CharField(help_text='User password', max_length=20)),
                ('date_of_birth', models.DateField(help_text='Birthday', null=True)),
                ('phone', models.CharField(help_text='User phone', max_length=15)),
                ('email', models.CharField(help_text='User e-mail', max_length=50)),
            ],
        ),
    ]
