# Generated by Django 2.2.4 on 2019-08-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='mail@mail.ru', help_text='User e-mail', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default='', help_text='User login', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', help_text='User password', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='strava_id',
            field=models.CharField(default=0, help_text='Stravas number user', max_length=10),
        ),
    ]
