# Generated by Django 2.2.4 on 2019-08-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190818_2149'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnRegUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='User name', max_length=30)),
                ('second_name', models.CharField(help_text='User second name', max_length=30)),
                ('phone', models.CharField(help_text='User phone', max_length=15)),
                ('email', models.CharField(default='mail@mail.ru', help_text='User e-mail', max_length=50)),
            ],
        ),
    ]
